### ISSUE TITLE
Add License checker

### ISSUE THREAD

**Issue by spacewander** [apache/apisix-python-plugin-runner#17]
For example:
https://github.com/apache/apisix-go-plugin-runner/blob/master/.github/workflows/license-checker.yml
https://github.com/apache/apisix-go-plugin-runner/blob/master/.licenserc.yaml

**Comment by jason-code78** [comment]
https://github.com/apache/apisix-go-plugin-runner/blob/master/.licenserc.admin

**Comment by shuaijinchao** [comment]
OK, support for license checking can be added in the next PR
