### ISSUE TITLE
How can i get request body from this plugin ?

### ISSUE THREAD

**Issue by kiritoscs** [apache/apisix-python-plugin-runner#37]
When I need to get the body in the request body, whether form or JSON, instead of using the URL param, how can I get it from the request in the plugin

**Comment by membphis** [comment]
ping @shuaijinchao

**Comment by shuaijinchao** [comment]
@kiritoscs because the format and structure of the body are more complex, the current version does not yet support this feature.

**Comment by membphis** [comment]
do we have any plan about this feature? @shuaijinchao

**Comment by kiritoscs** [comment]
And I have one more question.
Following the example of the stop plugin, I called self.stop() and rewrote Response.body. Why is nothing displayed in the browser? But can see it with Curl

**Comment by shuaijinchao** [comment]
> And I have one more question. Following the example of the stop plugin, I called self.stop() and rewrote Response.body. Why is nothing displayed in the browser? But can see it with Curl

You need to rewrite Contet-Type. In addition, self.stop() will be obsolete in subsequent versions. We need to align the logic with Go and Java. You can check the examples in the documentation in the master branch.

**Comment by shuaijinchao** [comment]
> do we have any plan about this feature?

Yes, we will support it in subsequent versions.
