### ISSUE TITLE
Does runner work with ext-plugin-post-resp?

### ISSUE THREAD

**Issue by dcuebas** [apache/apisix-python-plugin-runner#58]
Keep getting error: 

`[warn] 48#48: *256 [lua] init.lua:913: ERROR - unknown request` 

So, I want to verify that this runner works with `ext-plugin-post-resp`?
I don't get this error when using `ext-plugin-pre-req` or `ext-plugin-post-req`.

**Comment by SkyeYoung** [comment]
Not yet supported. But you can contribute code to the community if you are interested. Thx!
